project:
  type: website
  output-dir: docs

website:
  title: "Lab. de Agrometeorología"
  site-url: "https://agromet-lab.github.io"
  google-analytics: "G-GL7T3H2JHS"
  
  navbar:
    left:
      - text: "Qué hacemos"
        href: que_hacemos.qmd
      - text: "Ciencia en el campo"
        href: ciencia_campo.qmd
      - text: "Productos desarrollados"
        href: productos.qmd
      - text: "Servicios"
        href: servicios.qmd
      - text: "Novedades"
        href: novedades.qmd
      - text: "Publicaciones científicas"
        href: publicaciones.qmd
      - text: "Equipo"
        href: equipo.qmd
      - text: "Contacto"
        href: contacto.qmd

        
  page-footer:
    center: |
      <hr class="footer-line">
      <div class="footer-bottom">
        © <span id="year"></span> Laboratorio de Agrometeorología, INTA Balcarce. 
        Todos los derechos reservados. 
        Web diseñada por Nuria Lewczuk
        <a href="https://github.com/Nuria1982" 
           target="_blank" 
           class="footer-github">
          <img src="github.png" alt="github" />
        </a>
      </div>

format:
  html:
    theme:
      - Flatly
      - darkly
    
    css: styles.css
    include-after-body: footer-scripts.html
    respect-user-color-scheme: true
    toc: false


editor: source

