---
title: "Líneas de trabajo"
---



::: {.lineas-grid}

::: {.g-col-6 .text-center .lineas-card .lineas}
## <span class="card-title">Agua y cultivos</span>

Nos especializamos en comprender cómo el manejo afecta al consumo y la eficiencia en el uso del agua en los cultivos, en ambientes contrastantes en disponibilidad de agua. Nuestra aproximación es mediante experimentación a campo, a nivel de cultivo y de plantas individuales.
:::

::: {.g-col-6 .text-center .lineas-card .lineas}
## <span class="card-title">Gases de efecto invernadero (GEI)</span>
Nos enfocamos en la medición y análisis de las emisiones de óxido nitroso (N₂O), metano (CH₄) y dióxido de carbono (CO₂) en sistemas productivos agrícolas. Evaluamos cómo las prácticas de manejo, las condiciones ambientales y las características del suelo influyen en la dinámica de estos gases, integrando información meteorológica y edáfica para comprender los procesos que regulan las emisiones y contribuir al desarrollo de estrategias de mitigación.
:::

::: {.g-col-6 .text-center .lineas-card .lineas}
## <span class="card-title">Agrometeorología y climatología</span>
Caracterizamos el ambiente meteorológico y climático de la región mediante el análisis de variables de interés agronómico registradas en la estación meteorológica de la EEA INTA Balcarce, como base para la interpretación de procesos productivos y el desarrollo de herramientas de decisión.
:::

::: {.g-col-6 .text-center .lineas-card .lineas}
## <span class="card-title">Datos y herramientas</span>
Desarrollamos herramientas basadas en la integración de datos de campo, información meteorológica y análisis estadístico para apoyar la toma de decisiones en sistemas productivos. A través de plataformas interactivas y tableros digitales implementados en R, Quarto y Shiny, facilitamos la visualización, interpretación y uso de la información agroambiental para investigadores, técnicos y productores.
:::

:::



# Proyectos más recientes

- Adaptación del cultivo de maíz a deficiencias de agua en el suelo y reducción de emisiones de N2O, mediante el uso de hongos micorrícicos arbusculares (Lewczuk, N., Responsable).

- Tecnologías para la valorización de residuos agropecuarios y agroindustriales. PIETR-2025 (Echarte, L., Coordinadora).

- Bases ecofisiológicas de la respuesta de la eficiencia en el uso del agua en maíz ante variaciones en la densidad de plantas y cobertura del suelo. ANPCYT, PICT-2019 1444. (Echarte, L., Responsable).

- Cuantificación de emisiones de N₂O en cebada bajo distintas fuentes de fertilizantes nitrogenados, con y sin inhibidores de la nitrificación. (Lewczuk, N., Responsable).

- Análisis de flujos de CO₂ y CH₄ medidos mediante eddy covariance e dentificación de índices espectrales para caracterizar la dinámica productiva y ambiental del cultivo de arroz. (Lewczuk, N., Responsable).



<div class="volver-inicio">
<a href="index.html" class="volver-btn">⬆ Volver al inicio</a>
</div>

